# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 978a65f219ec8cd76aca87a1fb459b85a7132ec9c57a0a9abea63767b65128b2cf81e46ba1747aea5295111dca57711e8fcb61f716b61fa5a8f339b1b6f5dec0

test:
  secret_key_base: 32b5e1652e66413af7919f3b6de8a23f147389d47ed1b5ffea6663c04ef1627a5f39e9e39afb854b29502097543eea6d79d33062d3ac1f12065252b07c166efa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
